#!/usr/bin/env bash
# Generate a self-signed TLS cert for the OttoFlow validating webhook and create a Kubernetes secret.
# Optional/legacy: generates a Helm values fragment with webhook.certSecret and webhook.caBundle.
# The controller now uses the internal cert manager by default; this script is only for custom PKI overrides.
# Writes a Helm values fragment (YAML) for use with
# HELM_VALUES_FILE so the controller can serve webhooks and the API server can verify the connection.
#
# Usage:
#   ./scripts/generate-webhook-certs-kind.sh <namespace> [release_name] [output_yaml]
#
# Example (e2e):
#   ./scripts/generate-webhook-certs-kind.sh ottoflow ottoflow config/generated/e2e-webhook-values.yaml
#
# Then: helm template ... -f config/generated/e2e-webhook-values.yaml
# Or: make generate-manifests HELM_VALUES_FILE=config/generated/e2e-webhook-values.yaml IMG=... WORKFLOW_RUNNER_IMG=...

set -e

NAMESPACE="${1:?usage: $0 <namespace> [release_name] [output_yaml]}"
RELEASE_NAME="${2:-ottoflow}"
OUTPUT_YAML="${3:-}"

# Service name that the API server will connect to (must match ValidatingWebhookConfiguration and Service)
SVC_NAME="${RELEASE_NAME}-webhook"
SVC_DNS="${SVC_NAME}.${NAMESPACE}.svc"
COMMON_NAME="${SVC_DNS}"
SECRET_NAME="${RELEASE_NAME}-webhook-certs"

CERT_DIR="${CERT_DIR:-/tmp/ottoflow-webhook-certs-$$}"
mkdir -p "$CERT_DIR"
trap "rm -rf '$CERT_DIR'" EXIT

# Generate CA
openssl genrsa -out "$CERT_DIR/ca.key" 2048
openssl req -x509 -new -nodes -key "$CERT_DIR/ca.key" -sha256 -days 3650 -out "$CERT_DIR/ca.crt" \
  -subj "/CN=ottoflow-webhook-ca"

# Generate server cert (for the webhook service)
openssl genrsa -out "$CERT_DIR/tls.key" 2048
openssl req -new -key "$CERT_DIR/tls.key" -out "$CERT_DIR/tls.csr" \
  -subj "/CN=${COMMON_NAME}" \
  -addext "subjectAltName=DNS:${SVC_NAME},DNS:${SVC_DNS},DNS:localhost"

openssl x509 -req -in "$CERT_DIR/tls.csr" -CA "$CERT_DIR/ca.crt" -CAkey "$CERT_DIR/ca.key" \
  -CAcreateserial -out "$CERT_DIR/tls.crt" -sha256 -days 3650

# Create secret in cluster (kubectl must point to the target cluster, e.g. kind)
kubectl create namespace "$NAMESPACE" --dry-run=client -o yaml | kubectl apply -f -
kubectl create secret tls "$SECRET_NAME" -n "$NAMESPACE" \
  --cert="$CERT_DIR/tls.crt" --key="$CERT_DIR/tls.key" \
  --dry-run=client -o yaml | kubectl apply -f -

# caBundle for ValidatingWebhookConfiguration (base64-encoded CA cert)
CA_BUNDLE=$(base64 < "$CERT_DIR/ca.crt" | tr -d '\n')

if [ -n "$OUTPUT_YAML" ]; then
  mkdir -p "$(dirname "$OUTPUT_YAML")"
  cat > "$OUTPUT_YAML" << EOF
# Generated by scripts/generate-webhook-certs-kind.sh for webhook TLS
webhook:
  enabled: true
  certSecret: ${SECRET_NAME}
  caBundle: "${CA_BUNDLE}"
EOF
  echo "Wrote $OUTPUT_YAML (webhook.certSecret=${SECRET_NAME}, caBundle length=${#CA_BUNDLE})"
else
  echo "certSecret=${SECRET_NAME}"
  echo "caBundle=${CA_BUNDLE}"
fi
