{{- if and .Values.agentExecutor.enabled .Values.agentExecutor.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ottoflow.agentExecutor.serviceAccountName" . }}
  namespace: {{ include "ottoflow.namespace" . }}
  labels:
    {{- include "ottoflow.agentExecutor.labels.n4" . }}
  {{- with .Values.agentExecutor.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
