{{- if and .Values.rbac.create .Values.rbac.leaderElection.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ottoflow.fullname" . }}-leader-election-role
  namespace: {{ include "ottoflow.namespace" . }}
  labels:
    {{- include "ottoflow.labels.n4" . }}
    app.kubernetes.io/component: rbac
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
{{- end }}
